1097 wasa changes
PSMRI/Helpline1097-UI pull request #30
Opened 2024-12-13 10:33 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-12-16 08:54 UTC, drtechie commented on src/app/login/login.component.ts
> +          this.sessionstorage.setCookie('Jwttoken', tkn,1 );
@NKOKKILIGADDA87

2025-01-23 06:24 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 08:41 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 16:03 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 16:06 UTC, sandipkarmakar3 approved these changes
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-31 11:49 UTC, devikasuresh20 requested changes

2025-01-31 11:49 UTC, devikasuresh20 commented on src/app/services/config/config.service.ts
> +    private _commonBaseURL: String = `https://amritwprdev.piramalswasthya.org/commonapi-v3.0.0/`;
@sandipkarmakar3  Please keep common api version as v1.0

2025-01-31 11:49 UTC, devikasuresh20 commented on src/app/services/config/config.service.ts
> +    private _opencommonBaseURL: String = `${commonIP}commonapi-v3.0.0/`;
@sandipkarmakar3 Please keep all API versions as v1.0

2025-01-31 12:01 UTC, sandipkarmakar3 commented on src/app/services/config/config.service.ts
> +    private _commonBaseURL: String = `https://amritwprdev.piramalswasthya.org/commonapi-v3.0.0/`;
done

2025-01-31 12:01 UTC, sandipkarmakar3 commented on src/app/services/config/config.service.ts
> +    private _opencommonBaseURL: String = `${commonIP}commonapi-v3.0.0/`;
done

2025-01-31 12:04 UTC, devikasuresh20 approved these changes

2025-01-31 12:04 UTC, merged