Potentially unsafe external link, Client-side cross-site scripting, Overly permissive regular expression range
PSMRI/Helpline1097-UI pull request #8
Opened 2023-09-15 08:39 UTC by swetatech24

2023-09-15 11:36 UTC, devikasuresh20 approved these changes

2023-09-18 09:47 UTC, Anjana2310 requested changes

2023-09-18 09:47 UTC, Anjana2310 commented on src/index.html
>      // window.console.error = function() {}
@swetatech24 Please remove this commented code

2023-09-20 05:36 UTC, Anjana2310 approved these changes
@swetatech24 LGTM

2023-09-20 05:37 UTC, merged